// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNbkYhsiu3WVBJwnZHWs_wtZ25mOO-Uc4',
    appId: '1:184754421899:web:29ca6eeb2f358cb22e548e',
    messagingSenderId: '184754421899',
    projectId: 'saidi-sales',
    authDomain: 'saidi-sales.firebaseapp.com',
    storageBucket: 'saidi-sales.appspot.com',
    measurementId: 'G-G6CDWS8EGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3IyTeCnNeeVjT5xboO1Iv1lywt09xfOE',
    appId: '1:184754421899:android:e96065fd35f874252e548e',
    messagingSenderId: '184754421899',
    projectId: 'saidi-sales',
    storageBucket: 'saidi-sales.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1iN_727cFM13meUmY_PeFV8J66GI3GSU',
    appId: '1:184754421899:ios:1b6d1ca23fc9034f2e548e',
    messagingSenderId: '184754421899',
    projectId: 'saidi-sales',
    storageBucket: 'saidi-sales.appspot.com',
    iosBundleId: 'com.example.sales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1iN_727cFM13meUmY_PeFV8J66GI3GSU',
    appId: '1:184754421899:ios:44145abea66c6f2d2e548e',
    messagingSenderId: '184754421899',
    projectId: 'saidi-sales',
    storageBucket: 'saidi-sales.appspot.com',
    iosBundleId: 'com.example.sales.RunnerTests',
  );
}
